jwt:
  secret: "Z3VndXN0YXZvMTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MTIzNDU2Nzg5MA=="

spring:
  application:
    name: match
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    csrf:
#      enabled: false

